resource_group_name = "Devops-Projects"
location            = "East US"
vm_size             = "Standard_B1ms"
admin_username      = "adminuser"
admin_password      = "P@ssword1234!"
dns_prefix          = "testnode"
